name: git issues blog workflow

on: 
  push:
    branches:
      - master
    paths:
      - 'posts/*.md'
      - 'posts/*/*.md'
      - 'posts/*/*/*.md'


jobs:
  git-issues-blog:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Get git diff files
      run: |
        chmod +x git-issues-blog.sh
        ./git-issues-blog.sh
      shell:
        bash
    - name: Publish Issues
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTS_PATH: 'posts'
